// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NOR_24.Migrations
{
    [DbContext(typeof(DB_al78804))]
    partial class DB_al78804ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NOR_24.Models.RegistoUtilizador", b =>
                {
                    b.Property<int>("RegistoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Regime")
                        .HasColumnType("int");

                    b.Property<bool>("Valido")
                        .HasColumnType("bit");

                    b.HasKey("RegistoId");

                    b.HasIndex("RegistoId")
                        .IsUnique();

                    b.ToTable("RegistoUtilizador");
                });
#pragma warning restore 612, 618
        }
    }
}
