// <auto-generated />
using System;
using Estudo_Pratica2023.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estudo_Pratica2023.Migrations
{
    [DbContext(typeof(Estudo_Pratica2023Context))]
    partial class Estudo_Pratica2023ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Estudo_Pratica2023.Models.Aluno", b =>
                {
                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<float?>("Pratica")
                        .HasColumnType("real");

                    b.Property<float?>("Teorica")
                        .HasColumnType("real");

                    b.HasKey("Numero");

                    b.ToTable("Aluno");
                });
#pragma warning restore 612, 618
        }
    }
}
